import { z } from "zod";

export const zVideoTranscriptSegmentSchema = z.object({
  startMs: z.number().int().nonnegative(),
  endMs: z.number().int().nonnegative(),
  text: z.string(),
});

export type ZVideoTranscriptSegment = z.infer<
  typeof zVideoTranscriptSegmentSchema
>;

export const zVideoTranscriptSchema = z.object({
  bookmarkId: z.string(),
  language: z.string(),
  languageName: z.string().nullable(),
  isAutoGenerated: z.boolean(),
  isDefault: z.boolean(),
  segments: z.array(zVideoTranscriptSegmentSchema),
  createdAt: z.date(),
});

export type ZVideoTranscript = z.infer<typeof zVideoTranscriptSchema>;

export function videoTranscriptToText(
  transcript: Pick<ZVideoTranscript, "segments"> | null | undefined,
): string | null {
  if (!transcript) {
    return null;
  }
  const text = transcript.segments
    .map((segment) => segment.text)
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();
  return text || null;
}

export function videoTranscriptToTimestampedText(
  transcript: Pick<ZVideoTranscript, "segments"> | null | undefined,
): string | null {
  if (!transcript) return null;
  const text = transcript.segments
    .map((segment) => {
      const totalSeconds = Math.floor(segment.startMs / 1000);
      const hours = Math.floor(totalSeconds / 3600);
      const minutes = Math.floor((totalSeconds % 3600) / 60);
      const seconds = totalSeconds % 60;
      const timestamp =
        hours > 0
          ? `${hours}:${minutes.toString().padStart(2, "0")}:${seconds.toString().padStart(2, "0")}`
          : `${minutes}:${seconds.toString().padStart(2, "0")}`;
      return `[${timestamp}] ${segment.text.replace(/\s+/g, " ").trim()}`;
    })
    .join("\n")
    .trim();
  return text || null;
}
