name: Question / Support Request
description: Get help with anything related to Keepsake
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        For questions that are not bug reports or feature requests, use this repository's discussions if they are enabled.
