CREATE TABLE `videoTranscripts` (
	`bookmarkId` text NOT NULL,
	`language` text NOT NULL,
	`languageName` text,
	`isAutoGenerated` integer DEFAULT false NOT NULL,
	`isDefault` integer DEFAULT false NOT NULL,
	`segments` text NOT NULL,
	`createdAt` integer NOT NULL,
	PRIMARY KEY(`bookmarkId`, `language`),
	FOREIGN KEY (`bookmarkId`) REFERENCES `bookmarks`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `videoTranscripts_bookmarkId_idx` ON `videoTranscripts` (`bookmarkId`);--> statement-breakpoint
ALTER TABLE `highlights` ADD `startTime` integer;--> statement-breakpoint
ALTER TABLE `highlights` ADD `endTime` integer;--> statement-breakpoint
ALTER TABLE `highlights` ADD `transcriptLanguage` text;